apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
  name: quotes-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: quotes
  sessionAffinity: None
  type: LoadBalancer